import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import Providers from "./providers";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import "bootstrap/dist/css/bootstrap.min.css";
import "react-circular-progressbar/dist/styles.css";
import "@/styles/globals.css";
import "@/styles/card.css";
import "@/styles/about.css";
import "@/styles/aurora.css";

const barlowCondensed = Barlow_Condensed({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={barlowCondensed.className}>
        <Providers>
          {children}

          {/* ✅ GLOBAL TOASTS */}
          <ToastContainer
            position="top-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            pauseOnHover
            draggable
            theme="dark"
          />
        </Providers>
      </body>
    </html>
  );
}


{/*
import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Barlow_Condensed } from "next/font/google";
import Providers from "./providers";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-circular-progressbar/dist/styles.css';
import '@/styles/globals.css';
import '@/styles/card.css';
import '@/styles/about.css';
import '@/styles/aurora.css';


const barlowCondensed = Barlow_Condensed({
  weight: ["400"],     // THIN
  subsets: ["latin"],
  variable: "--font-barlow-condensed",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlowCondensed.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

*/}
