// app/layout.tsx
import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import Providers from "./providers";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import "bootstrap/dist/css/bootstrap.min.css";
import "react-circular-progressbar/dist/styles.css";
import "@/styles/globals.css";
import "@/styles/card.css";
import "@/styles/about.css";
import "@/styles/aurora.css";

// 🔹 SIDEBAR
import Nav from "@/components/nav/Nav";

// 🔹 MINI PLAYER
import { MiniPlayerProvider } from "@/components/videos/MiniPlayerContext";
import MiniPlayer from "@/components/videos/MiniPlayer";

const barlowCondensed = Barlow_Condensed({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Project Mirror",
  description: "AI-powered interactive platform",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={barlowCondensed.className}>
        <Providers>
          <MiniPlayerProvider>
            
            {/* 🔥 FLEX APP LAYOUT */}
            <div style={{ display: "flex" }}>
              
              {/* SIDEBAR */}
              <Nav />

              {/* MAIN CONTENT */}
              <main
                style={{
                  marginLeft: 80, // collapsed sidebar width
                  width: "100%",
                  minHeight: "100vh",
                  transition: "margin-left .3s ease",
                }}
              >
                {children}
              </main>

            </div>

            {/* 🔹 GLOBAL MINI PLAYER */}
            <MiniPlayer />

          </MiniPlayerProvider>

          {/* 🔔 GLOBAL TOASTS */}
          <ToastContainer
            position="top-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            pauseOnHover
            draggable
            theme="dark"
          />
        </Providers>
      </body>
    </html>
  );
}

{/*


import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import Providers from "./providers";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import "bootstrap/dist/css/bootstrap.min.css";
import "react-circular-progressbar/dist/styles.css";
import "@/styles/globals.css";
import "@/styles/card.css";
import "@/styles/about.css";
import "@/styles/aurora.css";

// 🔹 MINI PLAYER
import { MiniPlayerProvider } from "@/components/videos/MiniPlayerContext";
import MiniPlayer from "@/components/videos/MiniPlayer";

const barlowCondensed = Barlow_Condensed({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={barlowCondensed.className}>
        <Providers>
         
          <MiniPlayerProvider>
            {children}

           
            <MiniPlayer />
          </MiniPlayerProvider>

          <ToastContainer
            position="top-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            pauseOnHover
            draggable
            theme="dark"
          />
        </Providers>
      </body>
    </html>
  );
}





*/}
