"""add aurora_messages

Revision ID: 2163d50a278c
Revises: 9bfc832b80ed
Create Date: 2026-02-16 11:29:12.825496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2163d50a278c'
down_revision = '9bfc832b80ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aurora_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aurora_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aurora_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aurora_messages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurora_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aurora_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_aurora_messages_session_id'))

    op.drop_table('aurora_messages')
    # ### end Alembic commands ###
