"""add series avatar url to video

Revision ID: 243505f2d933
Revises: d3358284161a
Create Date: 2026-01-23 23:23:36.575962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243505f2d933'
down_revision = 'd3358284161a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_avatar_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('series_avatar_url')

    # ### end Alembic commands ###
