"""add aurora_session_summary

Revision ID: 250f0e7d92c8
Revises: fc6c88958789
Create Date: 2026-02-17 16:34:31.580161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250f0e7d92c8'
down_revision = 'fc6c88958789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aurora_session_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('primary_themes', sa.JSON(), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=50), nullable=True),
    sa.Column('session_outcome', sa.String(length=100), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('risk_flag', sa.Boolean(), nullable=True),
    sa.Column('recommendation_tag', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aurora_session_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aurora_session_summary_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aurora_session_summary_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aurora_session_summary_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurora_session_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aurora_session_summary_user_id'))
        batch_op.drop_index(batch_op.f('ix_aurora_session_summary_session_id'))
        batch_op.drop_index(batch_op.f('ix_aurora_session_summary_created_at'))

    op.drop_table('aurora_session_summary')
    # ### end Alembic commands ###
