"""initial tables

Revision ID: 4363ccdb7f7d
Revises: 
Create Date: 2025-11-17 10:40:03.561924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4363ccdb7f7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('is_anonymous_user', sa.Boolean(), nullable=True),
    sa.Column('allow_emotion_logging', sa.Boolean(), nullable=True),
    sa.Column('allow_face_storage', sa.Boolean(), nullable=True),
    sa.Column('relationship_stage', sa.String(length=50), nullable=True),
    sa.Column('preferred_tone', sa.String(length=50), nullable=True),
    sa.Column('comfort_level_score', sa.Float(), nullable=True),
    sa.Column('openness_level_score', sa.Float(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_face_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_emotion_analysis_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_oauth_id'), ['oauth_id'], unique=False)

    op.create_table('emotional_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('baseline_emotion_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_microexpressions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('average_gaze_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stress_indicator_level', sa.Float(), nullable=True),
    sa.Column('mood_variability_score', sa.Float(), nullable=True),
    sa.Column('daily_mood_streak', sa.Integer(), nullable=True),
    sa.Column('last_emotional_shift_at', sa.DateTime(), nullable=True),
    sa.Column('crisis_count', sa.Integer(), nullable=True),
    sa.Column('last_crisis_flag_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_embeddings')
    op.drop_table('emotional_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_oauth_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
