"""add analytics alerts

Revision ID: 512bc2f79333
Revises: e888248dcd13
Create Date: 2026-01-30 05:56:47.989357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512bc2f79333'
down_revision = 'e888248dcd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_alerts_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_alerts_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_alerts_video_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_alerts_alert_type'))
        batch_op.drop_index(batch_op.f('ix_analytics_alerts_admin_id'))

    op.drop_table('analytics_alerts')
    # ### end Alembic commands ###
