"""add aurora_relationship

Revision ID: 9bfc832b80ed
Revises: f3c2cdad0053
Create Date: 2026-02-16 11:07:50.698874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bfc832b80ed'
down_revision = 'f3c2cdad0053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aurora_relationship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('familiarity_score', sa.Integer(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ritual_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aurora_relationship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aurora_relationship_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurora_relationship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aurora_relationship_user_id'))

    op.drop_table('aurora_relationship')
    # ### end Alembic commands ###
