"""add meta_json to aurora_session_summary

Revision ID: ce347fdbcad8
Revises: e0a9715230b4
Create Date: 2026-02-18 22:02:32.963701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce347fdbcad8'
down_revision = 'e0a9715230b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurora_session_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('primary_themes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurora_session_summary', schema=None) as batch_op:
        batch_op.alter_column('primary_themes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('meta_json')

    # ### end Alembic commands ###
