"""add aurora_personality

Revision ID: e0a9715230b4
Revises: f4a3cf987bb5
Create Date: 2026-02-18 07:41:05.573749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0a9715230b4'
down_revision = 'f4a3cf987bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aurora_personality',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('verbosity', sa.String(length=50), nullable=False),
    sa.Column('pace', sa.String(length=50), nullable=False),
    sa.Column('directness', sa.String(length=50), nullable=False),
    sa.Column('probing_depth', sa.String(length=50), nullable=False),
    sa.Column('adaptive_score', sa.Float(), nullable=False),
    sa.Column('user_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('admin_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aurora_personality', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aurora_personality_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurora_personality', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aurora_personality_user_id'))

    op.drop_table('aurora_personality')
    # ### end Alembic commands ###
