"""add video_views table

Revision ID: e888248dcd13
Revises: 243505f2d933
Create Date: 2026-01-27 09:40:36.591121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e888248dcd13'
down_revision = '243505f2d933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_views_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_views_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_views_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_views_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_video_views_created_at'))

    op.drop_table('video_views')
    # ### end Alembic commands ###
