"""add video likes and reactions

Revision ID: f3c2cdad0053
Revises: 512bc2f79333
Create Date: 2026-02-03 23:22:30.663557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c2cdad0053'
down_revision = '512bc2f79333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'user_id', name='uq_video_user_reaction')
    )
    with op.batch_alter_table('video_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_reactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_reactions_video_id'), ['video_id'], unique=False)

    op.create_table('video_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_shares_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_shares_video_id'), ['video_id'], unique=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reel', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_videos_is_reel'), ['is_reel'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_is_reel'))
        batch_op.drop_column('is_reel')

    with op.batch_alter_table('video_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_shares_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_shares_user_id'))

    op.drop_table('video_shares')
    with op.batch_alter_table('video_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_reactions_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_reactions_user_id'))

    op.drop_table('video_reactions')
    # ### end Alembic commands ###
