"""add aurora_user_memory

Revision ID: f4a3cf987bb5
Revises: 250f0e7d92c8
Create Date: 2026-02-17 22:09:03.586931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4a3cf987bb5'
down_revision = '250f0e7d92c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aurora_user_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aurora_user_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aurora_user_memory_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_aurora_user_memory_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aurora_user_memory_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurora_user_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aurora_user_memory_user_id'))
        batch_op.drop_index(batch_op.f('ix_aurora_user_memory_session_id'))
        batch_op.drop_index(batch_op.f('ix_aurora_user_memory_key'))

    op.drop_table('aurora_user_memory')
    # ### end Alembic commands ###
