"""add aurora_emotions

Revision ID: fc6c88958789
Revises: 2163d50a278c
Create Date: 2026-02-17 16:17:16.545457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6c88958789'
down_revision = '2163d50a278c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aurora_emotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('emotion_label', sa.String(length=50), nullable=True),
    sa.Column('emotion_score', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('arousal', sa.Float(), nullable=True),
    sa.Column('dominance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['aurora_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aurora_emotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aurora_emotions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aurora_emotions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aurora_emotions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aurora_emotions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aurora_emotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aurora_emotions_user_id'))
        batch_op.drop_index(batch_op.f('ix_aurora_emotions_session_id'))
        batch_op.drop_index(batch_op.f('ix_aurora_emotions_message_id'))
        batch_op.drop_index(batch_op.f('ix_aurora_emotions_created_at'))

    op.drop_table('aurora_emotions')
    # ### end Alembic commands ###
